server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log

  - job_name: php_fpm_slow
    static_configs:
      - targets: [localhost]
        labels:
          job: php_fpm
          __path__: /var/log/php-slow.log

  - job_name: syslog
    journal:
      max_age: 12h
      labels:
        job: syslog

  - job_name: mysql
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql
          __path__: /var/log/mysql-slow.log
